### PR TITLE
Add ability to autocopy JSON

### PR DESCRIPTION
**Pull request by udoprog**
I have [an application I'm working on](https://github.com/udoprog/jpv) which can toggle the ability to process the clipboard content as JSON so that translations can be displayed alongside the text being analyzed.

I've also tried to modify the mime type where it is supported (e.g. `wl-copy --type application/json`) but this seems to largely be ignored in GNOME. It wouldn't hurt to set it though for future reference.

Tried to keep most things as-is and follow the style. But I don't work in Lua a lot so apologies if something is off.

### CODE REVIEW

**Comment by tatsumoto-ren** [comment]
I've added an option called `autoclip_method` to make it easier to switch between various ways we can send text to external apps.

**Comment by udoprog** [comment]
Oh. Yeah. You're getting somewhere! That made me realise I could use a custom command too. But I would appreciate two more knobs:

* The ability to specify the format *independently* of the pasting method. Currently if I specify a custom command I think it will just receive text and can't receive JSON.
* (Preferably) the ability to template the custom command so that it includes a mime type. Something like `jpv send-clipboard-data --type %m %d`. Maybe this is already supported, but I'm on my phone right now so can't easily check.

**Comment by udoprog** [comment]
> What do %m and %d stand for?

The `%m` argument would be the mime type in my example, and `%d` the data. `%s1` and `%s2` is fine too, with the caveat that `%s2` might not be defined.

**Comment by tatsumoto-ren** [comment]
Added `%MPV_PRIMARY%` and `%MPV_SECONDARY%` args that will be substituted when calling an external process.

**Pull request merged**
