### PR TITLE
Fix episode number parsing and add tests

### PR DESCRIPTION
**Pull request by Luukuton**
- Fixes a case where the wrong number was being parsed from the file name:
  - Before the ep number of `[*******] Sono Bisque Doll wa Koi wo Suru - 06 (1080p) [54E495D0].mkv` was 495
  - Now it's parsing it correctly as 06
- Added unit test for get_episode_number ~~with the help of [luaunit](https://github.com/bluebird75/luaunit)~~ with custom assert
  - Moved a couple functions to helpers.lua so that they can be tested independently without the `require("mp")`  etc.
  - FYI: test.lua doesn't have to be included in the release

Feel free to give feedback or suggestions about anything.

### CODE REVIEW

**Comment by Luukuton** [comment]
Tests can be run with: `lua test.lua`

**Comment by tatsumoto-ren** [comment]
Interesting.

Although you don't need to add a 3.5k SLOC file to the repo to test a function. `assertEquals` can be implemented in 10 lines of code. And it's better to replace `require('helpers')` with `local helpers = require('helpers')`.

**Comment by Luukuton** [comment]
Yeah I wasn't so sure about that. On the other hand it's a good testing library but not really that necessary for the functionality.

I'll remove it, and make the change with imports.

**Comment by tatsumoto-ren** [comment]
Sweet!

**Pull request merged**
