### PR TITLE
Support `audio_format=caf` for AnkiMobile

### PR DESCRIPTION
**Pull request by abdnh**

### CODE REVIEW

**Comment by tatsumoto-ren** [comment]
Since Apple's operating systems are malware, wouldn't merging this PR suggest that we affirm of the use of non-free software instead of encouraging people to ditch it?

**Comment by abdnh** [comment]
AnkiMobile is the sole way to support Anki's creator, and it essentially funds the development of the free computer version, even AnkiDroid to some degree. I use free alternatives whenever possible, but I think it's unrealistic for most people to completely ditch non-free software.

**Comment by tatsumoto-ren** [comment]
Ajatt-Tools is funded solely by donations. It's unfortunate that some people still spend money on proprietary software. Essentially they pay for being mistreated. And it makes the problem worse because it gives developers incentive to continue making proprietary software. 

It's totally possible to completely abandon proprietary software. I and many Ajatt-Tools members have done it. And we welcome others to do it too.

**Comment by rVnPower** [comment]
I don't really know what this PR offers.

**Comment by tatsumoto-ren** [comment]
Apparently the proprietary Anki app is not capable of playing ogg/opus files. But it can play the `caf` format. We can add support for the `caf` format, but there's a possibility that as a result people will be more likely to continue using iThings instead of getting rid of them.

**Pull request merged**
